apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-monitoring-kube-prometheus-alertmanager
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: "slack"
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 2h

    receivers:
      - name: "slack"
        slack_configs:
          - api_url: "https://hooks.slack.com/services/XXX/YYY/ZZZ"
            channel: "#alerts"
            send_resolved: true

      - name: "email"
        email_configs:
          - to: "you@example.com"
            from: "alertmanager@example.com"
            smarthost: "smtp.example.com:587"
            auth_username: "alertmanager@example.com"
            auth_password: "SMTP_PASSWORD"
            require_tls: true
